kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
  - name: test
    image: golang:1.13.0-buster
    commands:
      - go test -race

  - name: build
    image: golang:1.13-alpine3.10
    environment:
      CGO_ENABLED: "0"
    commands:
      - ln -s $PWD /build
      - cd /build
      - go mod download
      - mkdir release
      - GOOS=linux GOARCH=386 go build -ldflags "-s -w" -o "release/$DRONE_REPO_NAME-386" &
      - GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o "release/$DRONE_REPO_NAME-amd64" &
      - GOOS=linux GOARCH=arm go build -ldflags "-s -w" -o "release/$DRONE_REPO_NAME-arm" &
      - GOOS=linux GOARCH=arm64 go build -ldflags "-s -w" -o "release/$DRONE_REPO_NAME-arm64" &
      - GOOS=windows GOARCH=386 go build -ldflags "-s -w" -o "release/$DRONE_REPO_NAME-386.exe" &
      - GOOS=windows GOARCH=amd64 go build -ldflags "-s -w" -o "release/$DRONE_REPO_NAME-amd64.exe" &
      - wait

  - name: publish
    image: plugins/github-release
    when:
      event:
        - tag
    settings:
      api_key:
        from_secret: github_token
      files: "release/*"
