---
version: "3.7"

services:
  nginx:
    image: nginx:1.19.6
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/config:/etc/nginx/
    depends_on:
      - authelia
      - authelia-basic-2fa
    restart: unless-stopped

  authelia:
    image: authelia:4.26.0
    volumes:
      - authelia-data:/etc/authelia
      - authelia-var:/var/lib/authelia
    restart: unless-stopped

  authelia-basic-2fa:
    image: virb3/authelia-basic-2fa:2.1
    restart: unless-stopped

volumes:
  authelia-data:
  authelia-var:
