name: CI

on:
  push:
    branches: [v2]
    tags:
      - "*"
  pull_request:
    branches: [v2]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.API_GITHUB_TOKEN }}

      - name: Version
        id: semantic
        uses: cycjimmy/semantic-release-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}

      - name: Docker Prepare
        if: success() && startsWith(github.ref, 'refs/tags/')
        uses: crazy-max/ghaction-docker-buildx@v1.4.0

      - name: Docker Login
        if: success() && startsWith(github.ref, 'refs/tags/')
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin

      - name: Release Docker
        if: success() && startsWith(github.ref, 'refs/tags/')
        env:
          REPO: virb3/authelia-basic-2fa
        run: |
          . ./parse-version.sh
          docker buildx build \
            --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x \
            --push \
            --build-arg "VERSION=${VERSION}" \
            --tag "${REPO}:${VERSION}" \
            --tag "${REPO}:${VERSION_MAJOR}" \
            --tag "${REPO}:${VERSION_MINOR}" \
            --tag "${REPO}:latest" \
            --file ./Dockerfile ./

      - name: Release Binaries
        if: success() && startsWith(github.ref, 'refs/tags/')
        uses: goreleaser/goreleaser-action@v1.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
